name: Test release

on:
  push:
    branches:
      - master

jobs:
  Release:
    name: Test release
    runs-on: [ubuntu-latest]
    container:
      image: iotmod/goreleaser-cgo-cross-compiler:1.13.5
      volumes: [/repo]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test GoShimmer Release
        run: goreleaser --snapshot --skip-publish --rm-dist